### PR TITLE
Build-a-Pok-mon-Search-App

### PR DESCRIPTION
**Pull request by Marwa-Sadat**
1.	Creating the Repository:
	•	Repository “Pokemon-Search-App” created on GitHub. It includes all necessary project files: index.html, styles.css, and script.js. 📁
	2.	Setting Up the Project:
	•	Basic project structure set up with index.html for layout, styles.css for styling, and script.js for functionality. 🏗
	3.	Fetching Pokémon Data:
	•	Implemented API calls to the Pokémon API (https://pokeapi.co/) in script.js to fetch Pokémon details like name, type, and abilities. 🌐
	4.	Building the Search Interface:
	•	Designed a user-friendly search interface in index.html for Pokémon search input. Styled with styles.css to ensure visual appeal. 🔍
	5.	Displaying Results:
	•	Dynamically displaying search results on the web page, including Pokémon images, types, and abilities in a neat format. 📊
	6.	Making It Responsive:
	•	Ensured app responsiveness with CSS media queries, adjusting layout and design for mobile, tablet, and desktop screens. 📱

### CODE REVIEW

**Comment by Marwa-Sadat** [comment]
Screenshot 2024-07-13 085647
Hi@zinabbehzad  I hope you are well, please check my project.

**Comment by Marwa-Sadat** [comment]
Hi @zinabbehzad I hope you are well, please check my project
Screenshot 2024-07-13 092420

**Review by zainabbehzad — CHANGES_REQUESTED** [review]
@Marwa-Sadat 

🎉 Great Design Implemented
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Build-a-Pok-mon-Search-App project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
🧩Your design is responsive

Screenshot (61)

✔Your repo has a professional README.md file
* Please do not forget to add Deployment Link of your project in README.md

**Review by ahzamir — APPROVED** [review]
### Hi @Marwa-Sadat 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Pokemon Search App project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
